# .github/workflows/build-tailwind.yml

name: Build Tailwind

on:
  push:
    branches:
      - main

jobs:
  build-tailwind:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - name: Build Tailwind
        with:
          node-version: "18"
        run: npm run build
